os: windows 

sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov

script:
  - coverage run parser.py

after_success:
- codecov

notifications:
  email:
    - murilosilva.felipe@gmail.com
    - leozitor@gmail.com

jobs:
  include:
    - script: ./test 1 # uses the default stage name "test"
    - script: ./test 2
    - stage: deploy