os: windows 

sudo: false

language: python

python:
  - 2.7
  - 3.3

install:
  - pip install codecov

script:
  - coverage run parser.py

after_success:
- codecov

notifications:
  email:
    - murilosilva.felipe@gmail.com
    - leozitor@gmail.com


jobs:
  include:
    - stage: test
      script: ./parser teste1.pas
    - # stage name not required, will continue to use `test`
      script: ./parser teste4.pas
    - stage: deploy
      script: ./parser <<teste1.txt