os: windows 

sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov

script:
  - coverage run parser.py

after_success:
- codecov

notifications:
  email:
    - murilosilva.felipe@gmail.com
    - leozitor@gmail.com

jobs:
  include:
    - stage: test
      script: - coverage run parser.py
    - # stage name not required, will continue to use `test`
      script: - coverage run parser.py
    - stage: deploy
      script: - coverage run parser.py