os: windows 

sudo: false

language: python

python:
  - 2.7
  - 2.6

install:
  - pip install codecov

script:
  - coverage run parser.py

after_success:
- codecov

notifications:
  email:
    - murilosilva.felipe@gmail.com
    - leozitor@gmail.com

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - script: ./test 1 # uses the default stage name "test"
    - script: ./test 2
    - stage: deploy
      script: ./deploy target-1
    - script: ./deploy target-2