os: windows 

sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov

script:
  - coverage run parser.py

after_success:
- codecov

notifications:
  email:
    - murilosilva.felipe@gmail.com
    - leozitor@gmail.com